/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stdying_jni_Simple */

#ifndef _Included_com_stdying_jni_Simple
#define _Included_com_stdying_jni_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stdying_jni_Simple
 * Method:    getStringJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stdying_jni_Simple_getStringJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_stdying_jni_Simple
 * Method:    getTwoArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_stdying_jni_Simple_getTwoArray
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
