/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stdying_jni_Complex */

#ifndef _Included_com_stdying_jni_Complex
#define _Included_com_stdying_jni_Complex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stdying_jni_Complex
 * Method:    nativeSetName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_stdying_jni_Complex_nativeSetName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_stdying_jni_Complex
 * Method:    doCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stdying_jni_Complex_doCall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
