/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stdying_jni_JniCallJava */

#ifndef _Included_com_stdying_jni_JniCallJava
#define _Included_com_stdying_jni_JniCallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stdying_jni_JniCallJava
 * Method:    nativeSetName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_stdying_jni_JniCallJava_nativeSetName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_stdying_jni_JniCallJava
 * Method:    doCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stdying_jni_JniCallJava_doCall
  (JNIEnv *, jobject);

/*
 * Class:     com_stdying_jni_JniCallJava
 * Method:    doCallStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stdying_jni_JniCallJava_doCallStatic
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
